/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaproject;

import java.awt.datatransfer.StringSelection;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;

/**
 *
 * @author BORRAT Joan et SERRE Loïc
 */

/** password generation class */
public class pswgenerator extends javax.swing.JFrame {

        /**
         * Creates new form pswgenerator
         */
        /** class constructor */
        public pswgenerator(String s) {
                super(s);
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        /**
         * initialize all the components by putting them in the right place with the
         * right values
         */
        private void initComponents() {

                titlegenpsw = new javax.swing.JLabel();
                passwordsize = new javax.swing.JSlider();
                passwordfield = new javax.swing.JTextField();
                letterbox = new javax.swing.JCheckBox();
                numberbox = new javax.swing.JCheckBox();
                symbolbox = new javax.swing.JCheckBox();
                genbutton = new javax.swing.JButton();
                copypswbutton = new javax.swing.JButton();

                titlegenpsw.setFont(new java.awt.Font("Unispace", 0, 30)); // NOI18N
                titlegenpsw.setText("Générateur de mot de passe");

                passwordsize.setMajorTickSpacing(2);
                passwordsize.setMaximum(30);
                passwordsize.setMinimum(4);
                passwordsize.setPaintLabels(true);
                passwordsize.setPaintTicks(true);
                passwordsize.setToolTipText("");
                passwordsize.setValue(8);

                passwordfield.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
                passwordfield.setText("Selectionnez la taille ci-dessus");

                letterbox.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
                letterbox.setText("Lettres");

                numberbox.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
                numberbox.setText("Chiffres");

                symbolbox.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
                symbolbox.setText("Symboles");

                genbutton.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
                genbutton.setText("Générer");
                genbutton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                genbuttonActionPerformed(evt);
                        }
                });

                copypswbutton.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
                copypswbutton.setText("Copier");
                copypswbutton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                copypswbuttonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(154, 154, 154)
                                                                .addComponent(passwordsize,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                569, Short.MAX_VALUE)
                                                                .addGap(155, 155, 155))
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(titlegenpsw)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(passwordfield,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                387,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(copypswbutton))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(30, 30, 30)
                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(symbolbox)
                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                .addComponent(letterbox,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                85,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addComponent(numberbox,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                85,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(genbutton)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(74, 74, 74)
                                                                .addComponent(titlegenpsw)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                88, Short.MAX_VALUE)
                                                                .addComponent(passwordsize,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                76,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(passwordfield,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(copypswbutton,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(letterbox)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(numberbox)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(symbolbox)
                                                                .addGap(90, 90, 90)
                                                                .addComponent(genbutton)
                                                                .addGap(56, 56, 56)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        /**
         * Function to generate passwords with 3 different options. With numbers,
         * special characters or letters
         */
        private void passwordgenerator() {

                if (letterbox.isSelected() && numberbox.isSelected() && symbolbox.isSelected()) {
                        String characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*_=+-/.?<>)";
                        String password = "";
                        for (int i = 0; i < passwordsize.getValue(); i++) {
                                int index = (int) (characters.length() * Math.random());
                                password += characters.substring(index, index + 1);
                        }
                        passwordfield.setText(password);
                }

                else if (letterbox.isSelected() && !numberbox.isSelected() && !symbolbox.isSelected()) {
                        String characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
                        String password = "";
                        for (int i = 0; i < passwordsize.getValue(); i++) {
                                int index = (int) (characters.length() * Math.random());
                                password += characters.substring(index, index + 1);
                        }
                        passwordfield.setText(password);
                }

                else if (!letterbox.isSelected() && numberbox.isSelected() && !symbolbox.isSelected()) {
                        String characters = "0123456789";
                        String password = "";
                        for (int i = 0; i < passwordsize.getValue(); i++) {
                                int index = (int) (characters.length() * Math.random());
                                password += characters.substring(index, index + 1);
                        }
                        passwordfield.setText(password);
                }

                else if (!letterbox.isSelected() && !numberbox.isSelected() && symbolbox.isSelected()) {
                        String characters = "!@#$%^&*_=+-/.?<>)";
                        String password = "";
                        for (int i = 0; i < passwordsize.getValue(); i++) {
                                int index = (int) (characters.length() * Math.random());
                                password += characters.substring(index, index + 1);
                        }
                        passwordfield.setText(password);
                }

                else if (letterbox.isSelected() && numberbox.isSelected() && !symbolbox.isSelected()) {
                        String characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz01234567890123456789012345678901234567890123456789";
                        String password = "";
                        for (int i = 0; i < passwordsize.getValue(); i++) {
                                int index = (int) (characters.length() * Math.random());
                                password += characters.substring(index, index + 1);
                        }
                        passwordfield.setText(password);
                }

                else if (letterbox.isSelected() && !numberbox.isSelected() && symbolbox.isSelected()) {
                        String characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!@#$%^&*_=+-/.?<>)";
                        String password = "";
                        for (int i = 0; i < passwordsize.getValue(); i++) {
                                int index = (int) (characters.length() * Math.random());
                                password += characters.substring(index, index + 1);
                        }
                        passwordfield.setText(password);
                }

                else if (!letterbox.isSelected() && numberbox.isSelected() && symbolbox.isSelected()) {
                        String characters = "0123456789!@#$%^&*_=+-/.?<>)";
                        String password = "";
                        for (int i = 0; i < passwordsize.getValue(); i++) {
                                int index = (int) (characters.length() * Math.random());
                                password += characters.substring(index, index + 1);
                        }
                        passwordfield.setText(password);
                }

                else {
                        passwordfield.setText("Veuillez cocher au moins une case");
                }
        } // GEN-LAST:event_passwordsizeStateChanged

        /**
         * Actionperformed from the button to call the function which generates a
         * password
         */
        private void genbuttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_genbuttonActionPerformed
                // TODO add your handling code here:
                passwordgenerator();
        }// GEN-LAST:event_genbuttonActionPerformed

        /** Copy password to clipboard */
        private void copypswbuttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_copypswbuttonActionPerformed
                // TODO add your handling code here:
                String password = passwordfield.getText();
                StringSelection stringSelection = new StringSelection(password);
                Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard();
                clpbrd.setContents(stringSelection, null);
        }// GEN-LAST:event_copypswbuttonActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton copypswbutton;
        private javax.swing.JButton genbutton;
        private javax.swing.JCheckBox letterbox;
        private javax.swing.JCheckBox numberbox;
        private javax.swing.JTextField passwordfield;
        private javax.swing.JSlider passwordsize;
        private javax.swing.JCheckBox symbolbox;
        private javax.swing.JLabel titlegenpsw;
        // End of variables declaration//GEN-END:variables
}
